### ISSUE TITLE
No module named 'lti'

### ISSUE THREAD

**Issue by naelmusleh** [pylti/lti#36]
Hello I have django/python 2.7 project and I installed the lti module using pip. when trying to import the module in a python script, django raises an error that No module named 'lti'

I can import the module from the python shell though.

Please help

**Comment by ryanhiebert** [comment]
This indicates that somehow the environment for your Python isn't the same as for your script. Here's a couple suggestions:

1. Run `which python` to figure out where the python your session is using lives.
2. Run your script with `python yourscript.py` to see if it works that way.

Hopefully that gives you somewhere to look. I may be able to help more than that, but it will require more information, especially on what results you saw with those two suggestions.

**Comment by ryanhiebert** [comment]
I hope you've been able to solve your problem. Please let me know if there's more that I can do to help.
