### ISSUE TITLE
Duplicate query string value issue

### ISSUE THREAD

**Issue by andrew-gardener** [pylti/lti#50]
Currently the consumer or provider will include duplicate attributes that appear in the query string and body when calculating the signature.

This is an issue with some LTI consumers like Canvas that will duplicate any query string parameters into its launch request body (using the parameter only once in the signature)

**Comment by ryanhiebert** [comment]
That's very odd. It seems like this would be a bug in Canvas, since they aren't signing the request following the OAuth spec? Is there a related issue on the instructure/canvas-lms repository?

**Comment by andrew-gardener** [comment]
Nevermind, looked into the spec more and found out it is a Canvas implementation issue (https://github.com/instructure/canvas-lms/issues/600). Sorry for the trouble

**Comment by ryanhiebert** [comment]
I do think, if there's an issue in canvas that needs fixed, that it may be reasonable for this library to put in place a workaround.
