### ISSUE TITLE
Non Compliant LTI Systems

### ISSUE THREAD

**Issue by subssn21** [pylti/lti#54]
I would love to hear what people do in the case that they have a Tool Consumer that is sending non-compliant LTI parameters. 

Looking at the code there is a section for canvas -- LAUNCH_PARAMS_CANVAS

I have a vendor who doesn't want to remove their non-standard parameters:
basiclti_submit
launch_url

Which is causing the launch to fail when I receive it:

lti.launch_params:InvalidLaunchParamError: launch_url is not a valid launch param
File "/opt/nogginllc/learnwell/env3.5/lib/python3.5/site-packages/lti/launch_params.py", line 198, in __setitem__

There are a few ways I can think of to handle these issues:
1. (I hate this idea) Add the non-standard params to the launch_params.py file.
2. (I hate this idea) Monkey patch the launch params
3. (I hate this less but this is a bad idea) Remove validation altogether
4. (Getting Better) Make Launch Parameter validation optional
5. (Best Idea, but not sure easiest way to implement) Allow passing additional allowed parameters at runtime.

I would like to hear thoughts about this

**Comment by ryanhiebert** [comment]
I agree with your assessment of the options. 5 would be my preference, barring issues that I don't forsee making that unreasonable to implement.

**Comment by subssn21** [comment]
I always get who is the ToolConsumer and who is the ToolProvider mixed up, but my software is the provider and the Consumer is passing non-standard Launch Params.

Just looked through the code, and the easiest way I can see to do this is the following:
Change the ToolProvider class to have a class attribute that represents the LaunchParams class.
This would allow subclasses of ToolProvider to supply their own subclass of LaunchParams.

**Comment by subssn21** [comment]
So I started working on implementing this, and realized the LaunchParams arrays are defined at the module level and not in the LaunchParams class. 

We are now really getting into the philosophical area of how to properly make these changes. The changes at the ToolProvider Level are like two lines of code, the problem comes with the LaunchParams since the arrays aren't part of the class and the valid_param function is also at the module level.

We really need to move at least the valid_param function into the LaunchParam class so it can be subclassed and changed. Is that ok? Should we move the arrays into the class as well?

**Comment by ryanhiebert** [comment]
Let's do what we can to avoid breaking changes, but yes, I think that needs to go into the class. This could work by duplicating the function currently called as a method, or by having it call the function by default. As long as the interface isn't needlessly removed.

I'd have to look at the particular code in question,but I think there's a reasonable argument to make that we don't really want the function to keep existing, so I'd be inclined to raise a deprecation warning in that function, and we can remove it in the future when we release a major version.

**Comment by subssn21** [comment]
This issue is fixed in the master branch
